openapi: 3.0.0
info:
  title: CTF Management API
  description: 'API for managing CTF (Capture The Flag) games, teams, users, and services.'
  contact: {}
  version: 1.0.0
servers:
  - url: 'https://api.ctf01d.com'
    description: Production server
  - url: 'https://api.staging.ctf01d.com'
    description: Staging server
  - url: 'http://localhost:4102'
    description: Local server
paths:
  /users:
    get:
      tags:
        - Users
      summary: List all users
      operationId: listUsers
      parameters: []
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
                x-content-type: application/json
    post:
      tags:
        - Users
      summary: Create a new user
      operationId: createUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '201':
          description: User created successfully
  '/users/{id}':
    get:
      tags:
        - Users
      summary: Get a user by ID
      operationId: getUserById
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Detailed information of a user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      tags:
        - Users
      summary: Update a user
      operationId: updateUser
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: User updated successfully
    delete:
      tags:
        - Users
      summary: Delete a user
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '204':
          description: User deleted successfully
  /games:
    get:
      tags:
        - Games
      summary: List all games
      operationId: listGames
      parameters: []
      responses:
        '200':
          description: A list of games
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
                x-content-type: application/json
    post:
      tags:
        - Games
      summary: Create a new game
      operationId: createGame
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
        required: true
      responses:
        '201':
          description: Game created successfully
  '/games/{id}':
    get:
      tags:
        - Games
      summary: Get a game by ID
      operationId: getGameById
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Detailed information of a game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
    put:
      tags:
        - Games
      summary: Update a game
      operationId: updateGame
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
        required: true
      responses:
        '200':
          description: Game updated successfully
    delete:
      tags:
        - Games
      summary: Delete a game
      operationId: deleteGame
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '204':
          description: Game deleted successfully
  /teams:
    get:
      tags:
        - Teams
      summary: List all teams
      operationId: listTeams
      parameters: []
      responses:
        '200':
          description: A list of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
                x-content-type: application/json
    post:
      tags:
        - Teams
      summary: Create a new team
      operationId: createTeam
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
        required: true
      responses:
        '201':
          description: Team created successfully
  '/teams/{id}':
    get:
      tags:
        - Teams
      summary: Get a team by ID
      operationId: getTeamById
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Detailed information of a team
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
    put:
      tags:
        - Teams
      summary: Update a team
      operationId: updateTeam
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
        required: true
      responses:
        '200':
          description: Team updated successfully
    delete:
      tags:
        - Teams
      summary: Delete a team
      operationId: deleteTeam
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '204':
          description: Team deleted successfully
  /results:
    get:
      tags:
        - Results
      summary: List all results
      operationId: listResults
      parameters: []
      responses:
        '200':
          description: A list of game results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'
                x-content-type: application/json
    post:
      tags:
        - Results
      summary: Create a new result
      operationId: createResult
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Result'
        required: true
      responses:
        '201':
          description: Result created successfully
  '/results/{id}':
    get:
      tags:
        - Results
      summary: Get a result by ID
      operationId: getResultById
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Detailed information of a result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
  /services:
    get:
      tags:
        - Services
      summary: List all services
      operationId: listServices
      parameters: []
      responses:
        '200':
          description: A list of services
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'
                x-content-type: application/json
    post:
      tags:
        - Services
      summary: Create a new service
      operationId: createService
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
        required: true
      responses:
        '201':
          description: Service created successfully
  '/services/{id}':
    get:
      tags:
        - Services
      summary: Get a service by ID
      operationId: getServiceById
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Detailed information of a service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
    put:
      tags:
        - Services
      summary: Update a service
      operationId: updateService
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
        required: true
      responses:
        '200':
          description: Service updated successfully
    delete:
      tags:
        - Services
      summary: Delete a service
      operationId: deleteService
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '204':
          description: Service deleted successfully
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier for the user
        username:
          type: string
          description: The name of the user
        role:
          type: string
          description: 'The role of the user (admin, player)'
        avatar_url:
          type: string
          description: URL to the user's avatar
        status:
          type: string
          description: 'Status of the user (active, disabled)'
      example:
        role: role
        avatar_url: avatar_url
        id: id
        username: username
        status: status
    Game:
      required:
        - end_time
        - id
        - start_time
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the game
        start_time:
          type: string
          description: The start time of the game
          format: date-time
        end_time:
          type: string
          description: The end time of the game
          format: date-time
        description:
          type: string
          description: A brief description of the game
      example:
        start_time: '2000-01-23T04:56:07.000Z'
        end_time: '2000-01-23T04:56:07.000Z'
        description: description
        id: id
    Result:
      required:
        - game_id
        - id
        - rank
        - score
        - team_id
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the result entry
        team_id:
          type: string
          description: Identifier of the team this result belongs to
        game_id:
          type: string
          description: Identifier of the game this result is for
        score:
          type: integer
          description: The score achieved by the team
        rank:
          type: integer
          description: The rank achieved by the team in this game
      example:
        score: 0
        rank: 6
        id: id
        team_id: team_id
        game_id: game_id
    Service:
      required:
        - author
        - id
        - is_public
        - name
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the service
        name:
          type: string
          description: Name of the service
        author:
          type: string
          description: Author of the service
        logo_url:
          type: string
          description: URL to the logo of the service
        description:
          type: string
          description: A brief description of the service
        is_public:
          type: boolean
          description: Boolean indicating if the service is public
      example:
        logo_url: logo_url
        author: author
        name: name
        is_public: true
        description: description
        id: id
    Team:
      required:
        - id
        - team_name
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the team
        team_name:
          type: string
          description: Name of the team
        description:
          type: string
          description: A brief description of the team
        university:
          type: string
          description: University or institution the team is associated with
        social_links:
          type: string
          description: JSON string containing social media links of the team
        avatar_url:
          type: string
          description: URL to the team's avatar
      example:
        avatar_url: avatar_url
        university: university
        social_links: social_links
        description: description
        id: id
        team_name: team_name
  links: {}
  callbacks: {}
security: []
